### ISSUE TITLE
only two gpus

### ISSUE THREAD

**Issue by zjk958162734** [lxtGH/GALD-Net#14]
Sorry to interrupt you, I want to ask, if I only have two GPUs, each with 12GB, can I run your semantic segmentation code? If I run, what needs to be modified, thank you

**Comment by lxtGH** [comment]
Yes, you can run it but I can garuntee the final performance because the batchsize is too small.

1. modify the shell scripts "python -m torch.distributed.launch --nproc_per_node=2" 


2.reduce the crop size. 

You can reproduce the results for the fast segmentation models in my another repo: 
https://github.com/lxtGH/Fast_Seg
